// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjq36WdhwQ4V7pfeXef0J0WDpQ8Hc-swE',
    appId: '1:103638061442:web:e98f7989acd49583e4bf9b',
    messagingSenderId: '103638061442',
    projectId: 'slf1-4e867',
    authDomain: 'slf1-4e867.firebaseapp.com',
    storageBucket: 'slf1-4e867.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSOnQ4cGrbFh7ipoU2FXmlUUaAmApHrI',
    appId: '1:103638061442:android:006375813c3de3f6e4bf9b',
    messagingSenderId: '103638061442',
    projectId: 'slf1-4e867',
    storageBucket: 'slf1-4e867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD08aKCLR8HCH8IcqSr0e0eiFrV7APhUGc',
    appId: '1:103638061442:ios:bd9c3425d15b6d0fe4bf9b',
    messagingSenderId: '103638061442',
    projectId: 'slf1-4e867',
    storageBucket: 'slf1-4e867.firebasestorage.app',
    iosBundleId: 'com.example.slf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD08aKCLR8HCH8IcqSr0e0eiFrV7APhUGc',
    appId: '1:103638061442:ios:bd9c3425d15b6d0fe4bf9b',
    messagingSenderId: '103638061442',
    projectId: 'slf1-4e867',
    storageBucket: 'slf1-4e867.firebasestorage.app',
    iosBundleId: 'com.example.slf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjq36WdhwQ4V7pfeXef0J0WDpQ8Hc-swE',
    appId: '1:103638061442:web:16e2b9419d7f74b8e4bf9b',
    messagingSenderId: '103638061442',
    projectId: 'slf1-4e867',
    authDomain: 'slf1-4e867.firebaseapp.com',
    storageBucket: 'slf1-4e867.firebasestorage.app',
  );
}
